### ISSUE TITLE
Axis different from Kitti ground truth

### ISSUE THREAD

**Issue by zhaoymn** [fferroni/lidar_odometry_and_mapping#4]
Hello,

Your code works perfectly. The only problem is that the result your code produce is not in the same coordinate. Could you please change the transformation matrix a little bit to make it consistent that the evaluation tool can be directly applied on the results?

Thank you!

**Comment by fferroni** [comment]
well, i wanted it in a different coordinate system so that's why i made it that way. if you want to change it, or make it an option, make a PR :)
